# Generated by Django 5.2.5 on 2025-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("refunded", "refunded"),
                ],
                db_index=True,
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
