# Generated by Django 5.2.5 on 2025-08-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
