# Generated by Django 5.2.5 on 2025-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_booking_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("none", "Unpaid"),
                    ("paid", "Paid"),
                    ("refund_pending", "Refund Pending"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
