# Generated by Django 5.2.5 on 2025-08-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
