# Generated by Django 5.2.5 on 2025-09-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
