# Generated by Django 5.2.5 on 2025-08-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_booking_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="refund_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="refund_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
