# Generated by Django 5.2.5 on 2025-08-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_booking_refund_amount_booking_refund_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("refund_pending", "Refund Pending"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="Unpaid",
                max_length=20,
            ),
        ),
    ]
