# Generated by Django 5.2.5 on 2025-08-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refund_pending", "Refund Pending"),
                    ("refunded", "Refunded"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
